package com.njusoft.its.websocket;
/** 
*
* @author 作者 E-mail:857332533@qq.com 
* @date 创建时间：2017年10月23日 上午10:38:42 
* @version 1.0 
* @since JDK 1.7
*/
public enum WebSocketDataTypes {
	
	LOGIN("LOGIN"),
	CUR_LINES("CUR_LINES"),
	CONNECTED_LINE("CONNECTED_LINE"),
	REAL_STATION("REAL_STATION"),
	REAL_LOCATION("REAL_LOCATION"),
	REAL_EVENT("REAL_EVENT"),
	REAL_ENTERSTATION("REAL_ENTERSTATION"),
	REAL_OVERSPEED("REAL_OVERSPEED"),
	REAL_DISPATCHPLAN("REAL_DISPATCHPLAN"),
	REAL_BUSINUPFIELD("REAL_BUSINUPFIELD"),
	REAL_BUSINDOWNFIELD("REAL_BUSINDOWNFIELD"),
	REAL_COUNT("REAL_COUNT"),
	REAL_LINE("REAL_LINE"),
	REAL_EMPLOYEE("REAL_EMPLOYEE"),
	REAL_BUS("REAL_BUS"),
	REAL_BUSDRIVER("REAL_BUSDRIVER"),
	REAL_REALLINEINDEXS("REAL_REALLINEINDEXS"),
	REAL_LINETIMERUNTIME("REAL_LINETIMERUNTIME"),
	REAL_PERSONTIME("REAL_PERSONTIME"),
	REAL_SYSTEMCONFIG("REAL_SYSTEMCONFIG"),
	LOGIN_USERNAME("LOGIN_USERNAME"),
	REAL_STARTEDDISPATCHPLAN("REAL_STARTEDDISPATCHPLAN"),
	REAL_BUSOFFLINE("REAL_BUSOFFLINE"),
	REAL_LINESTATE("REAL_LINESTATE"),
	REAL_LINERUNINTERVAL("REAL_LINERUNINTERVAL"),
	REAL_LINENOTOPERATIONBUSSTATE("REAL_LINENOTOPERATIONBUSSTATE"),
	REAL_BUSSTATE("REAL_BUSSTATE");
	
	private String name;
	
	public String getName(){
		return this.name;
	}
	
	private WebSocketDataTypes(String name){
		this.name = name;
	}
}
